### ISSUE TITLE
寻医问药网抓取要求

### ISSUE THREAD

**Issue by zixin** [haxibiao/dongdianyi#1]
懂点医要抓取的文章和网站要求！

　　寻医问药网

　　域名：wck.xywy.com

　　权重：百度权重7 移动权重8 搜狗权重4 谷歌权重6

　　需要抓取的分类/频道：抓取热门疾病分类所用病种的文章。

　　懂点医需要抓取的文章内部内容片段：文字少于500字的文章不要，病种文章标题包括症状、原因、护理、预防都要抓取，比如心脏病的症状，心脏病的原因等，标题包含“医院”的文章不要。

**Comment by caizhigang1997** [comment]
DEV本地测试通过，PM随时可以REVIEW

**Comment by zixin** [comment]
抓取回来的网站，可以根据网站分类吗？比如，寻医问药放到一个文件夹里，飞华健康网放到一个文件夹里，到时候也可以方便去除一个网站的脏格式，也可以方便编辑文章的规格，不要抓取回来的所有文章都放懂点医里面，看起来很乱！

**Comment by caizhigang1997** [comment]
没问题，分类可以手动指定的。
