### ISSUE TITLE
上传的文章格式要求！

### ISSUE THREAD

**Issue by zixin** [haxibiao/dongdianyi#23]
文章要有行距，文章段落空格两个字段，网站文章添加至少三张图片！

**Comment by wangxinaa** [comment]
这个是指什么爬虫上传的文章吗

**Comment by zixin** [comment]
是的，网站批量上传的文章

**Comment by ivanzhang2** [comment]
以后这类信息写个邮件让相关人知道，或者写个blog 当做工作手册，　具体问题具体log issue, 方便resolve
