### ISSUE TITLE
懂点医问答里面的回答信息删除了在问答首页还是会显示

### ISSUE THREAD

**Issue by zixin** [haxibiao/dongdianyi#31]
![01.png](https://images.zenhubusercontent.com/5aa9ef3e4b5806bc2bcaeb8e/a14ad5d9-285a-4692-aef6-1ae506877cd3)懂点医问答里面的回答信息删除了在问答首页还是会显示!

**Comment by pengconguses1** [comment]
这个问题已经解决~
