### ISSUE TITLE
改一下懂点医的title、mate

### ISSUE THREAD

**Issue by zixin** [haxibiao/dongdianyi#33]
title：懂点医_专业提供养生医疗保健科普知识与问答互动服务平台

Description：懂点医,专业提供优质的医疗健康科普和医患互动问答平台，包括养生,保健,中医,健康科普,男科,妇科,育儿,减肥,急救,中医,美容,饮食等频道。

Keywords:健康科普,医疗知识,健康资讯,疾病大全,医患问答

**Comment by pengconguses1** [comment]
已经添加上

**Comment by zixin** [comment]
只在首页里面有的！
