### ISSUE TITLE
懂点医底部添加

### ISSUE THREAD

**Issue by zixin** [haxibiao/dongdianyi#34]
懂点医底部加一个“合作伙伴”放懂点药的链接和懂美味的链接还有微信二维码https://dongdianyi.com/article/1866（链接绑定），“帮助中心”绑定https://dongdianyi.com/dongdianyilidexiaomimi  加上网站的备案号 冀ICP备17022765号-5

**Comment by pengconguses1** [comment]
已经完成

**Comment by zixin** [comment]
懂点医底部把合作伙伴改成懂美味，加上网站超链接。

**Comment by pengconguses1** [comment]
已经修改

**Comment by zixin** [comment]
把合作伙伴直接改成懂美味

**Comment by pengconguses1** [comment]
已经修改完成
