### ISSUE TITLE
懂点医专题修改

### ISSUE THREAD

**Issue by zixin** [haxibiao/dongdianyi#36]
懂点医专题修改，我现在整理懂点医的专题栏目，有助于搜索引擎的优化，我把没有文章的专题都删除了，但是到急求药品不可以删除，老是显示里面有文章不可以删除，但是点进去，里面又没有文章。

**Comment by zixin** [comment]
还有养生学堂视频合集

**Comment by pengconguses1** [comment]
实际上该专题下有文章 只是没有收录  提示是对的～
