### ISSUE TITLE
懂点医添加编辑源代码窗口

### ISSUE THREAD

**Issue by zixin** [haxibiao/dongdianyi#40]
懂点医添加编辑源代码窗口，我需要修改图片的alt属性有助于网站优化，也可以直接放入视频的代码，不用直接占用我们空间的内存！

**Comment by yasin-wang** [comment]
前端可以自定义图片描述，但是提交后后台会自动修改Alt属性，所以需要后端帮忙修改。☺️

**Comment by zixin** [comment]
那我要彭聪后台关了alt属性，那我要手动去改网站的两千多的图片属性吗？不是吧！

**Comment by yasin-wang** [comment]
要想自定义的话必须要手动的吧🤕，我觉得就主动修改主配图，然后剩下的后台根据主配图自动修改。

**Comment by zixin** [comment]
那我之前的文章就不改了，你就帮我把所有文章第一张图片的图片属性改成文章的标题！

**Comment by zixin** [comment]
还有文章的第一段文字也添加一个标题！

**Comment by yasin-wang** [comment]
这个应该还是得后端哥哥帮忙😁

**Comment by zixin** [comment]
我知道，我不是没有Assignees给你吗？我把你关了啊！为什么你还可以收到！

**Comment by zixin** [comment]
彭聪，我在想，我给你关键词，然后你放在同类型的文章专题文章的图片属性中可以吗？

**Comment by pengconguses1** [comment]
可以啊  没问题，我刚刚查了下编辑器的文档 发现编辑器作者没有支持显示源代码的功能,

要实现只能让前端修改一下js...老王 看你的了

**Comment by pengconguses1** [comment]
我已经把图片的alt添加给去除了 只会动第一个图片的alt

**Comment by yasin-wang** [comment]
为什么非得显示源代码，不是有弹出框能改吗

**Comment by yasin-wang** [comment]
编辑图片的Alt属性，编辑器已经具备这个功能，如果是有其它特殊需要的话一起沟通😁
