### ISSUE TITLE
中医养生专题文章上传规则

### ISSUE THREAD

**Issue by zixin** [haxibiao/dongdianyi#54]
去掉文章类所以这种形式的div，还有最后<p></p>

<div class="dis_intro">
							<h3>
<b>感冒</b>介绍</h3>
							<div class="intr_detial">感冒，总体上分为普通感冒和流行感冒，在这里先讨论普通感冒。普通感冒，祖国医学称&amp;q…[详细]
</div>
							<div class="intr_lj">
<span class="intr_lj_l"><h4><li style="display:none;">感冒的</li>病因</h4>|<h4><li style="display:none;">感冒的</li>症状</h4>|<h4><li style="display:none;">感冒的</li>治疗</h4>|<h4><li style="display:none;">感冒的</li>预防</h4></span><span class="intr_search">搜索：感冒</span>
</div>
						</div>
						
						<div class="extra"></div>
					</div>					<div class="key_word" id="box_232">
						
						
						<div class="dis_intro">
							<h3>
<b>先兆流产</b>介绍</h3>
							<div class="intr_detial">先兆流产指妊娠周前出现少量阴道道流血和(或)下腹疼痛宫口未开胎膜未破妊娠物…[详细]
</div>
							<div class="intr_lj">
<span class="intr_lj_l"><h4><li style="display:none;">先兆流产的</li>病因</h4>|<h4><li style="display:none;">先兆流产的</li>症状</h4>|<h4><li style="display:none;">先兆流产的</li>治疗</h4>|<h4><li style="display:none;">先兆流产的</li>预防</h4></span><span class="intr_search">搜索：先兆流产</span>
</div>
						</div>
						
						<div class="extra"></div>
					</div>
                    <div class="detail_con">
                       <p></p>

**Comment by zixin** [comment]
还有去掉<u>胎儿</u>   文章类的下划线

**Comment by zixin** [comment]
去掉文章的下划线

**Comment by zixin** [comment]
去掉网站类最底部的（责任编辑：实习***）名字是不一样的

**Comment by zixin** [comment]
还有删除文章底部的所有内容

<p align="right">（责任编辑：实习刘素玲）</p>
                    </div>
					<script type="text/javascript">detail.loadTips('.tips');</script><div class="writing_ad">
						<script type="text/javascript">BAIDU_CLB_fillSlot("177466");</script>
</div> 
                    <div class="page_byphone cc">
                        
                    </div>
                    <div class="share_big cc">
                        <script type="text/javascript" src="http://img1.99.com.cn/js/pcbaidushare_24.js?1" charset="gbk"></script>
</div>
		    
					<div class="recom_read">						 
						<div class="recom_read_con">
							<div class="read_con_l">
								<h3>今日推荐</h3>
								<dl>
<dt><img src="http://img.99.com.cn/uploads/161228/408-16122Q0345H12.jpg?180_110" alt="煎煮中药要盖盖子吗 中药煎煮不宜太浓"></dt>
									<dd>煎煮中药要盖盖子吗 </dd>
								</dl>
<dl>
<dt><img src="http://img.99.com.cn/uploads/161227/408-16122G02541312.jpg?180_110" alt="冬季泡脚水里加一物能驱寒祛湿"></dt>
									<dd>冬季泡脚水里加一物能</dd>
								</dl>
</div>
							
								
							</div>
						</div>
					</div>
					<div style="margin-top:15px;"><script>document.write(unescape('%3Cdiv id="hm_t_96156"%3E%3C/div%3E%3Cscript charset="utf-8" src="http://crs.baidu.com/t.js?siteId=28dc9e1760657360ac975d8555de2fcc&planId=96156&async=0&referer=') + encodeURIComponent(document.referrer) + '&title=' + encodeURIComponent(document.title) + '&rnd=' + (+new Date) + unescape('"%3E%3C/script%3E'));</script></div>

					
</div>			
					<script>detail.init();</script>
                
                    </div>
                    
                    <div class="article-foot">
    <a class="notebook" href="#">
        <i class="iconfont icon-wenji">
        </i>
        <span>
            新闻
        </span>
    </a>
    <div class="copyright" data-original-title="转载请联系作者获得授权，并标注“哈希表作者”。" data-toggle="tooltip">
        © 著作权归作者所有
    </div>
</div>                </div>


                

            </div>
        </div>
    </div>
    <div class="note-bottom">
        <div class="container">
            <div class="col-xs-12 col-md-8 col-md-offset-2">
                <div class="recommend-note">
                    <div class="recommend-title">
                        推荐阅读
                    </div>
                    <ul class="article-list">
                        <li class="article-item ">
        <div class="content">
        <a class="headline paper-title" href="/article/99223" target="_blank">
            <span>
                老年人如何抗脑病衰老
            </span>
        </a>
        <p class="abstract">
            
					
					本文导读：老年人之所以称之为老年人就是因为不仅是身体的...
        </p>
        <div class="author">
                    </div>
    </div>
</li>
<li class="article-item ">
        <div class="content">
        <a class="headline paper-title" href="/article/99559" target="_blank">
            <span>
                女性怎么根据体质减肥
            </span>
        </a>
        <p class="abstract">
            
					
					本文导读：吃出来的健康，同样，疾病也是吃出来的，很多人...
        </p>
        <div class="author">
                    </div>
    </div>
</li>
<li class="article-item /img/ys99/sijiyingshi/柠檬蜂蜜水DIY 喝出别样味道.jpg">
        <a class="wrap-img" href="/article/93352" target="_blank">
        <img src=""/>
    </a>
        <div class="content">
        <a class="headline paper-title" href="/article/93352" target="_blank">
            <span>
                柠檬蜂蜜水DIY 喝出别样味道
            </span>
        </a>
        <p class="abstract">
            
					
					本文导读：柠檬含有非常丰富的维生素，能够防止肌肤黑色素...
        </p>
        <div class="author">
                    </div>
    </div>
</li>
<li class="article-item /img/ys99/sijiyingshi/入冬后老人要严防五种疾病.jpg">
        <a class="wrap-img" href="/article/91182" target="_blank">
        <img src=""/>
    </a>
        <div class="content">
        <a class="headline paper-title" href="/article/91182" target="_blank">
            <span>
                入冬后老人要严防五种疾病
            </span>
        </a>
        <p class="abstract">
            
					
					本文导读：进入冬季之后，老年人身体的各项机能会开始下降...
        </p>
        <div class="author">
                    </div>
    </div>
</li>
<li class="article-item /img/ys99/sijiyingshi/秋季吃螃蟹要注意哪些？.jpg">
        <a class="wrap-img" href="/article/96660" target="_blank">
        <img src=""/>
    </a>
        <div class="content">
        <a class="headline paper-title" href="/article/96660" target="_blank">
            <span>
                秋季吃螃蟹要注意哪些？
            </span>
        </a>
        <p class="abstract">
            
					
					本文导读：现在秋季是吃螃蟹的季节，那么秋季如何吃螃蟹呢...
        </p>
        <div class="author">
                    </div>
    </div>
</li>
<li class="article-item ">
        <div class="content">
        <a class="headline paper-title" href="/article/97268" target="_blank">
            <span>
                夏季有哪些膳食有助于消暑
            </span>
        </a>
        <p class="abstract">
            
					
					本文导读：天热了，人们的胃口会随着燥热的天气而变小，人...
        </p>
        <div class="author">
                    </div>
    </div>
</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

        

        <div class="side-tool">
            <go-top></go-top>
                    </div>

    </div>

**Comment by pengconguses1** [comment]
已经修复

**Comment by zixin** [comment]
那个下划线解决了吗？

**Comment by zixin** [comment]
标题加上-健康咨询，如果下滑线解决了，就用文章底部加上：更多有关中医养生的内容，可以点击查看【中医养生】（这里还是加上超链接）专题栏目--（懂点医），如果下滑线没有解决就用最后一个下划线的词，链接到专题的连接，

**Comment by pengconguses1** [comment]
下划线已经解决了
